<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/09 12:49:19

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'sqlite:/home/vagrant/htdocs/pictureGallery/data/sandbox.db',
  'username' => 'root',
  'password' => NULL,
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
